{
   'led_name':'red',
   'path':'/gpfs/slac/lsst/fs1/g/data/R_and_D/RTM-006/180420/ccob',
   'tmp_dir':'/home/combet/tmp_new/',
   'eo_data_path':'/gpfs/slac/lsst/fs1/g/data/jobHarness/jh_archive-test/LCA-11021_RTM/LCA-11021_RTM-006-Dev/5867D/collect_raft_results/v0/38904',
   'xpos':'295.0',
   'ypos':'195.0'
}